from . import apollocar3d
from . import cifar10
from . import coco
from . import wholebody
from . import furniture
from . import keypoint5
from . import pascal3d
from . import chair
from . import sofa
